= OpenShift Windows Containers

Welcome to the OpenShift Windows Containers quickstart demo guide!

This guide is designed to help you explore the capabilities (and limitations) of Windows Containers on OpenShift. As we approach General Availability (GA), this guide will evolve into a full workshop.

Before we begin, a few notes:
You should have received an email from the RHPDS system. I assume you have it—otherwise, how would you be reading this? :)

== Release Notes

- Updated and enhanced the NetCandyStore modules.
- Upgraded OpenShift to version 4.12.
- Added a new set of instructions.
- *Note:* Starting with version 4.11, the external Prometheus console is no longer available. This workshop is not intended for use with Prometheus or Grafana.

The email you received contains all the details needed to test or demo Windows Containers, including instructions for SSH-ing into the bastion host. Go ahead and do that now. Here’s an example:

[source,shell]
----
ssh chernand-redhat.com@bastion.lax-e35b.sandbox886.opentlc.com
----

When prompted for a password, enter the one provided in the email. I recommend copying your SSH key to the bastion host to simplify access. Unless otherwise stated, all commands in this guide assume you’re working from the bastion host.

Once you’re logged in, you’re ready to start!

